# Generated by Django 5.0.2 on 2024-02-18 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Painting',
            fields=[
                ('ID', models.IntegerField(primary_key=True, serialize=False)),
                ('Title', models.CharField(max_length=200)),
                ('Artist', models.CharField(max_length=200)),
                ('Description', models.CharField(max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('Price', models.IntegerField()),
                ('image_url', models.CharField(max_length=1000, null=True)),
            ],
        ),
    ]
