# Generated by Django 5.0.2 on 2024-02-29 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PaintingApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='painting',
            name='image_url',
        ),
        migrations.AddField(
            model_name='painting',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='paintings/'),
        ),
        migrations.AlterField(
            model_name='painting',
            name='ID',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
