# Generated by Django 5.0.2 on 2024-02-11 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PaintingApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='painting',
            name='Image_url',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='painting',
            name='Price',
            field=models.IntegerField(),
        ),
    ]
