# Generated by Django 5.0.2 on 2024-02-29 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PaintingApp', '0002_remove_painting_image_url_painting_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='painting',
            name='ID',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
