# Generated by Django 5.0.2 on 2024-03-01 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PaintingApp', '0003_alter_painting_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='painting',
            name='ID',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
